import { Check, LockKeyhole } from "lucide-react";
import { requireLeadership } from "@/lib/auth/require-leadership";
import { getSeasons } from "@/lib/seasons";

import { StartSeasonForm, CloseSeasonForm } from "@/components/history-forms";
import { startSeason, closeSeason } from "./actions";
export const metadata = { title: "Settings" };
export default async function Settings() {
  const { profile } = await requireLeadership();
  const seasons = await getSeasons();
  return <div className="space-y-8"><div className="page-heading"><div><span className="eyebrow text-primary">Workspace settings</span><h1>A private space for leadership.</h1><p>Your access and the seasons available to this workspace.</p></div></div><section className="panel"><div className="section-heading"><h2>Your account</h2><span className="inline-flex items-center gap-1.5 text-xs font-semibold text-primary"><Check size={14} /> Active leadership</span></div><dl className="grid gap-6 p-6 sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Name</dt><dd className="mt-2 text-sm font-semibold">{profile.full_name || "Not set"}</dd></div><div><dt className="text-xs text-muted-foreground">Email address</dt><dd className="mt-2 break-all text-sm font-semibold">{profile.email || "Not set"}</dd></div></dl><p className="border-t border-border px-6 py-4 text-xs leading-5 text-muted-foreground">Account and membership changes are managed by your workspace administrator in Supabase. Self-service membership edits aren’t available.</p></section><section className="panel"><div className="section-heading"><h2>Recruiting seasons</h2><span className="text-xs text-muted-foreground">Preserve recruiting history</span></div><ul className="divide-y divide-border">{seasons.map(season => <li key={season.id} className="px-6 py-5"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-sm font-semibold">{season.name}</p><p className="mt-1 text-xs text-muted-foreground">{season.status === "closed" ? "Historical season" : "Active recruiting season"}</p></div><span className="status-tag">{season.status === "closed" ? "Closed" : season.is_current ? "Current" : "Active"}</span></div>{season.status === "active" ? <CloseSeasonForm year={season.year} closeAction={closeSeason.bind(null,season.id,season.year)}/> : <p className="mt-3 text-xs text-muted-foreground">{season.closed_at ? "Closed "+new Date(season.closed_at).toLocaleString("en-US",{timeZone:"UTC"})+" UTC by "+season.closed_by_name : "Closure date and author were not recorded for this earlier season."}</p>}</li>)}</ul>{!seasons.length && <p className="p-6 text-sm text-muted-foreground">No seasons are configured yet.</p>}<div className="border-t border-border"><StartSeasonForm year={Math.max(1999,...seasons.map(season=>season.year))+1} startAction={startSeason}/></div></section><div className="flex gap-3 text-xs leading-6 text-muted-foreground"><LockKeyhole size={16} className="mt-1 shrink-0" /><p>This application is private. Real player data belongs only in the private recruiting environment—not in this public repository or a future portfolio demo.</p></div></div>;
}
