import { Check, LockKeyhole } from "lucide-react";
import { requireLeadership } from "@/lib/auth/require-leadership";
import { getSeasons } from "@/lib/seasons";

export const metadata = { title: "Settings" };
export default async function Settings() {
  const { profile } = await requireLeadership();
  const seasons = await getSeasons();
  return <div className="space-y-8"><div className="page-heading"><div><span className="eyebrow text-primary">Workspace settings</span><h1>A private space for leadership.</h1><p>Your access and the seasons available to this workspace.</p></div></div><section className="panel"><div className="section-heading"><h2>Your account</h2><span className="inline-flex items-center gap-1.5 text-xs font-semibold text-primary"><Check size={14} /> Active leadership</span></div><dl className="grid gap-6 p-6 sm:grid-cols-2"><div><dt className="text-xs text-muted-foreground">Name</dt><dd className="mt-2 text-sm font-semibold">{profile.full_name || "Not set"}</dd></div><div><dt className="text-xs text-muted-foreground">Email address</dt><dd className="mt-2 break-all text-sm font-semibold">{profile.email || "Not set"}</dd></div></dl><p className="border-t border-border px-6 py-4 text-xs leading-5 text-muted-foreground">Account and membership changes are managed by your workspace administrator in Supabase. Self-service edits aren’t part of Phase 1.</p></section><section className="panel"><div className="section-heading"><h2>Recruiting seasons</h2><span className="text-xs text-muted-foreground">Read-only</span></div><ul className="divide-y divide-border">{seasons.map(season => <li key={season.id} className="flex items-center justify-between gap-4 px-6 py-5"><div><p className="text-sm font-semibold">{season.name}</p><p className="mt-1 text-xs text-muted-foreground">{season.status === "closed" ? "Historical season" : "Active recruiting season"}</p></div><span className="status-tag">{season.is_current ? "Current" : "Closed"}</span></li>)}</ul>{!seasons.length && <p className="p-6 text-sm text-muted-foreground">No seasons are configured yet.</p>}</section><div className="flex gap-3 text-xs leading-6 text-muted-foreground"><LockKeyhole size={16} className="mt-1 shrink-0" /><p>This application is private. Real player data belongs only in the private recruiting environment—not in this public repository or a future portfolio demo.</p></div></div>;
}
