import Link from "next/link";
import { evaluationAttributes,displayRating,type EvaluationSummary,type EvaluationAction } from "@/lib/evaluation-policy";
import { EvaluationForm } from "./evaluation-form";

export function Evaluations({summary,saveAction,profileUrl,seasonName,userId}:{summary:EvaluationSummary;saveAction?:EvaluationAction;profileUrl:string;seasonName:string;userId:string}) {
 return <section id="evaluations" className="panel min-w-0 scroll-mt-6" aria-labelledby="evaluations-title">
  <div className="section-heading"><h2 id="evaluations-title">Evaluations · {seasonName}</h2><span className="text-xs text-muted-foreground">{summary.count} submitted</span></div>
  <p className="px-6 pt-5 text-xs leading-5 text-muted-foreground">Individual evaluations and averages are visible before you submit your own. Each evaluator has one evaluation per season. N/A is excluded from numeric averages.</p>
  {saveAction ? <EvaluationForm own={summary.own} saveAction={saveAction} profileUrl={profileUrl}/> : <p className="p-6 text-sm text-muted-foreground">Historical evaluations · Read-only.</p>}
  <div className="border-t border-border p-6"><h3 className="text-sm font-semibold">Attribute averages</h3><p className="mt-2 text-xs text-muted-foreground">All submitted evaluations count equally, including retained evaluations from former leaders.</p><dl className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{evaluationAttributes.map(({key,label})=>{const average=summary.averages[key];return <div key={key} className="rounded-md border border-border p-4"><dt className="text-xs font-semibold text-muted-foreground">{label}</dt><dd className="mt-3 text-xl font-medium" aria-label={`${label} average`}>{average.mean===null?"N/A":`${average.mean.toFixed(2)} / 5`}</dd><dd className="mt-2 text-xs text-muted-foreground">{average.count} rated · {average.na} N/A</dd></div>;})}</dl></div>
  <div className="border-t border-border px-6 py-5"><h3 className="text-sm font-semibold">Evaluator comparison</h3><p className="mt-2 text-xs text-muted-foreground">Individual submitted ratings. N/A means not assessed; it is never a zero.</p></div>
  {summary.rows.length ? <div role="region" aria-label="Individual evaluations comparison table" tabIndex={0} className="overflow-x-auto"><table className="w-full min-w-[800px] text-left text-xs"><caption className="sr-only">Individual evaluations for {seasonName}</caption><thead className="bg-slate-50"><tr><th scope="col" className="px-6 py-4">Evaluator</th>{evaluationAttributes.map(({key,label})=><th key={key} scope="col" className="px-3 py-4">{label}</th>)}<th scope="col" className="px-6 py-4">Updated (UTC)</th></tr></thead><tbody className="divide-y divide-border">{summary.rows.map(row=><tr key={row.id}><th scope="row" className="px-6 py-4 font-semibold">{row.evaluator_name}{row.evaluator_id===userId?" (you)":""}</th>{evaluationAttributes.map(({key})=><td key={key} className="px-3 py-4">{displayRating(row[key])}</td>)}<td className="px-6 py-4"><time dateTime={row.updated_at}>{new Date(row.updated_at).toLocaleString("en-US",{timeZone:"UTC"})}</time></td></tr>)}</tbody></table></div> : <p className="px-6 pb-6 text-sm text-muted-foreground">No evaluations submitted for this season yet.</p>}
  {summary.count>25&&<nav aria-label="Evaluation pages" className="flex flex-wrap gap-4 border-t border-border p-4 text-xs"><span>Page {summary.page} of {Math.ceil(summary.count/25)}</span>{summary.page>1&&<Link className="text-primary underline" href={profileUrl+"&evaluationPage="+(summary.page-1)+"#evaluations"}>Previous evaluations</Link>}{summary.page*25<summary.count&&<Link className="text-primary underline" href={profileUrl+"&evaluationPage="+(summary.page+1)+"#evaluations"}>Next evaluations</Link>}</nav>}
 </section>;
}
