// Entirely invented people, teams, and scenarios. Never load private data here.
const leaders = ['Riley Chen', 'Morgan Hale', 'Avery Brooks'];

const sampleProspects = [
  {
    id: 'demo-1',
    name: 'Darius Holloway',
    position: 'Handler',
    location: 'Brooklyn, NY',
    teams: 'Harbor Union',
    email: 'darius.holloway@example.com',
    stage: 'Unknown Prospect',
    priority: 'High',
    owner: null,
    nextAction: null,
    followUp: '2027-01-10',
    projections: [
      'Compete for a reset-handler role',
      'Develop as a reliable late-count option',
      'Potential to lead a second offensive unit',
    ],
    evaluations: [
      {name: leaders[0], scores: [4, 3, null, 5, 4, 4]},
      {name: leaders[1], scores: [3, 4, 3, 4, null, 5]},
    ],
    priorOutcome: 'Cut–Encourage to Return',
  },
  {
    id: 'demo-2',
    name: 'Evan Mercer',
    position: 'Cutter',
    location: 'Jersey City, NJ',
    teams: 'Metro Flight',
    email: 'evan.mercer@example.com',
    stage: 'Known Prospect',
    priority: 'High',
    owner: null,
    nextAction: null,
    followUp: '2027-01-10',
    projections: [
      'Earn minutes as a downfield defender',
      'Add more initiating-cut responsibility',
      'Potential matchup defender in high-leverage points',
    ],
    evaluations: [
      {name: leaders[0], scores: [5, 3, 4, 4, 4, 3]},
      {name: leaders[2], scores: [4, 3, 5, 4, 4, null]},
    ],
    priorOutcome: 'Practice Player',
  },
  {
    id: 'demo-3',
    name: 'Malik Rowan',
    position: 'Handler',
    location: 'Queens, NY',
    teams: 'Northstar Ultimate',
    email: 'malik.rowan@example.com',
    stage: 'Confirmed for Tryouts',
    priority: 'High',
    owner: leaders[2],
    nextAction: 'Confirm availability for the February tryout date',
    followUp: '2027-01-10',
    projections: [
      'Stabilize a defensive-unit handler group',
      'Expand pull-play throwing responsibilities',
      'Potential two-way rotation contributor',
    ],
    evaluations: [
      {name: leaders[0], scores: [4, 4, 3, 5, 4, 4]},
      {name: leaders[1], scores: [4, 5, 3, 4, 4, 4]},
    ],
    priorOutcome: 'Cut–Encourage to Return',
  },
  {
    id: 'demo-4',
    name: 'Theo Bennett',
    position: 'Cutter',
    location: 'Philadelphia, PA',
    teams: 'Riverside Forge',
    email: 'theo.bennett@example.com',
    stage: 'Unknown Prospect',
    priority: 'Medium',
    owner: leaders[0],
    nextAction: 'Ask a regional contact for a recent film reference',
    followUp: '2027-01-10',
    projections: [
      'Adjust to the pace of the club season',
      'Develop into a dependable isolation cutter',
      'Potential offensive rotation contributor',
    ],
    evaluations: [
      {name: leaders[1], scores: [4, 3, 3, 4, null, 4]},
      {name: leaders[2], scores: [4, 4, 3, 5, 4, 4]},
    ],
    priorOutcome: 'Practice Player',
  },
  {
    id: 'demo-5',
    name: 'Jonah Serrano',
    position: 'Handler',
    location: 'New Haven, CT',
    teams: 'Liberty Line',
    email: 'jonah.serrano@example.com',
    stage: 'Known Prospect',
    priority: 'Medium',
    owner: leaders[1],
    nextAction: 'Schedule a call about travel expectations',
    followUp: '2027-01-18',
    projections: [
      'Provide steady backfield depth',
      'Take on more pressure-breaking possessions',
      'Potential leader within the handler group',
    ],
    evaluations: [
      {name: leaders[0], scores: [3, 4, 3, 5, 4, 5]},
      {name: leaders[2], scores: [3, 4, null, 4, 5, 5]},
    ],
  },
  {
    id: 'demo-6',
    name: 'Caleb Price',
    position: 'Cutter',
    location: 'Boston, MA',
    teams: 'Beacon Athletic',
    email: 'caleb.price@example.com',
    stage: 'Confirmed for Tryouts',
    priority: 'Medium',
    owner: leaders[2],
    nextAction: 'Send the tryout weekend logistics',
    followUp: '2027-01-18',
    projections: [
      'Compete for a defensive cutting role',
      'Improve continuation decisions after the catch',
      'Potential primary matchup defender',
    ],
    evaluations: [
      {name: leaders[0], scores: [5, 3, 5, 4, 4, 4]},
      {name: leaders[1], scores: [5, 4, 4, 4, 4, 3]},
    ],
  },
  {
    id: 'demo-7',
    name: 'Andre Whitaker',
    position: 'Handler',
    location: 'Washington, DC',
    teams: 'Capital Foundry',
    email: 'andre.whitaker@example.com',
    stage: 'Unknown Prospect',
    priority: null,
    owner: leaders[0],
    nextAction: 'Review film from the fall regional final',
    followUp: '2027-01-18',
    projections: [
      'Show consistency against elite marks',
      'Grow into a secondary offensive initiator',
      'Potential crossover option on either unit',
    ],
    evaluations: [
      {name: leaders[1], scores: [3, 4, 3, 4, 3, null]},
      {name: leaders[2], scores: [4, 4, 3, 4, 4, 4]},
    ],
  },
  {
    id: 'demo-8',
    name: 'Miles Lawson',
    position: 'Cutter',
    location: 'Providence, RI',
    teams: 'Ocean State Current',
    email: 'miles.lawson@example.com',
    stage: 'Known Prospect',
    priority: null,
    owner: leaders[1],
    nextAction: 'Invite to the next preseason throwing session',
    followUp: '2027-01-18',
    projections: [
      'Contribute as an athletic depth cutter',
      'Refine team-defense communication',
      'Potential core defensive-unit contributor',
    ],
    evaluations: [
      {name: leaders[0], scores: [5, 3, 4, 4, 5, 4]},
      {name: leaders[2], scores: [4, 3, 4, 5, 4, 4]},
    ],
  },
  {
    id: 'demo-9',
    name: 'Noah Ellison',
    position: 'Handler',
    location: 'Albany, NY',
    teams: 'Hudson Current',
    email: 'noah.ellison@example.com',
    stage: 'Confirmed for Tryouts',
    priority: null,
    owner: leaders[2],
    nextAction: 'Confirm arrival time and carpool needs',
    followUp: null,
    projections: [
      'Demonstrate command of the reset space',
      'Build chemistry with a new cutting group',
      'Potential offensive-system specialist',
    ],
    evaluations: [
      {name: leaders[0], scores: [4, 4, 3, 4, null, 4]},
      {name: leaders[1], scores: [null, null, null, null, null, null]},
    ],
  },
  {
    id: 'demo-10',
    name: 'Isaiah Foster',
    position: 'Cutter',
    location: 'New York, NY',
    teams: 'Independent',
    email: 'isaiah.foster@example.com',
    stage: 'Unknown Prospect',
    priority: null,
    owner: leaders[0],
    nextAction: 'Make an initial introduction after league finals',
    followUp: null,
    projections: [
      'Establish a role through preseason practices',
      'Develop more complete throwing options',
      'Potential rotational offensive cutter',
    ],
    evaluations: [],
  },
];

export const demoData = {
  currentYear: 2027,
  today: '2027-01-15',
  leaders,
  attributes: ['Athleticism', 'Offensive Ability', 'Defensive Ability', 'Coachability', 'On Field Vibes', 'Off Field Vibes'],
  stages: ['Unknown Prospect', 'Known Prospect', 'Confirmed for Tryouts'],
  prospects: sampleProspects.map(({priorOutcome, ...person}, index) => ({
    id: person.id,
    name: person.name,
    position: person.position,
    location: person.location,
    teams: person.teams,
    email: person.email,
    seasons: [
      {
        year: 2027,
        status: 'active',
        stage: person.stage,
        priority: person.priority,
        owner: person.owner,
        nextAction: person.nextAction,
        followUp: person.followUp,
        outcome: null,
        projections: person.projections,
        evaluations: person.evaluations,
      },
      ...(priorOutcome ? [{
        year: 2026,
        status: 'closed',
        stage: 'Confirmed for Tryouts',
        priority: index < 2 ? 'High' : 'Medium',
        owner: leaders[2],
        nextAction: 'Close the loop after the 2026 selection process',
        followUp: '2026-03-01',
        outcome: priorOutcome,
        projections: [
          'Build consistency in a defined role',
          'Grow into a dependable rotation option',
          'Develop leadership through club experience',
        ],
        evaluations: [{name: leaders[2], scores: [3, 3, 2, 4, null, 4]}],
      }] : []),
    ],
  })),
};
